import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class MazeWorld here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class MazeWorld extends World
{

    /**
     * Constructor for objects of class MazeWorld.
     * 
     */
    public MazeWorld()
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.
        super(600,600, 1); 
        prepare();
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        MazeBarrier mazeBarrier = new MazeBarrier();
        addObject(mazeBarrier,2*50,10*50);
        MazeBarrier mazeBarrier2 = new MazeBarrier();
        addObject(mazeBarrier2,2*50,11*50);
        MazeBarrier mazeBarrier3 = new MazeBarrier();
        addObject(mazeBarrier3,2*50,9*50);
        MazeBarrier mazeBarrier4 = new MazeBarrier();
        addObject(mazeBarrier4,0,10*50);
        MazeBarrier mazeBarrier5 = new MazeBarrier();
        addObject(mazeBarrier5,0,9*50);
        MazeBarrier mazeBarrier6 = new MazeBarrier();
        addObject(mazeBarrier6,0,8*50);
        MazeBarrier mazeBarrier7 = new MazeBarrier();
        addObject(mazeBarrier7,1*50,8*50);
        MazeBarrier mazeBarrier8 = new MazeBarrier();
        addObject(mazeBarrier8,5*50,7*50);
        mazeBarrier8.setLocation(2*50,8*50);
        MazeBarrier mazeBarrier9 = new MazeBarrier();
        addObject(mazeBarrier9,3*50,8*50);
        MazeBarrier mazeBarrier10 = new MazeBarrier();
        addObject(mazeBarrier10,4*50,8*50);
        MazeBarrier mazeBarrier11 = new MazeBarrier();
        addObject(mazeBarrier11,5*50,8*50);
        mazeBarrier3.setLocation(3*50,7*50);
        MazeBarrier mazeBarrier12 = new MazeBarrier();
        addObject(mazeBarrier12,0,5*50);
        MazeBarrier mazeBarrier13 = new MazeBarrier();
        addObject(mazeBarrier13,1*50,5*50);
        MazeBarrier mazeBarrier14 = new MazeBarrier();
        addObject(mazeBarrier14,2*50,5*50);
        MazeBarrier mazeBarrier15 = new MazeBarrier();
        addObject(mazeBarrier15,2*50,4*50);
        MazeBarrier mazeBarrier16 = new MazeBarrier();
        addObject(mazeBarrier16,2*50,3*50);
        MazeBarrier mazeBarrier17 = new MazeBarrier();
        addObject(mazeBarrier17,2*50,2*50);
        MazeBarrier mazeBarrier18 = new MazeBarrier();
        addObject(mazeBarrier18,2*50,1*50);
        MazeBarrier mazeBarrier19 = new MazeBarrier();
        addObject(mazeBarrier19,4*50,2*50);
        MazeBarrier mazeBarrier20 = new MazeBarrier();
        addObject(mazeBarrier20,5*50,2*50);
        MazeBarrier mazeBarrier21 = new MazeBarrier();
        addObject(mazeBarrier21,6*50,3*50);
        MazeBarrier mazeBarrier22 = new MazeBarrier();
        addObject(mazeBarrier22,6*50,4*50);
        MazeBarrier mazeBarrier23 = new MazeBarrier();
        addObject(mazeBarrier23,4*50,4*50);
        MazeBarrier mazeBarrier24 = new MazeBarrier();
        addObject(mazeBarrier24,6*50,1*50);
        MazeBarrier mazeBarrier25 = new MazeBarrier();
        addObject(mazeBarrier25,4*50,0);
        MazeBarrier mazeBarrier26 = new MazeBarrier();
        addObject(mazeBarrier26,5*50,6*50);
        mazeBarrier26.setLocation(5*50,6*50);
        MazeBarrier mazeBarrier27 = new MazeBarrier();
        addObject(mazeBarrier27,5*50,6*50);
        MazeBarrier mazeBarrier28 = new MazeBarrier();
        addObject(mazeBarrier28,6*50,6*50);
        MazeBarrier mazeBarrier29 = new MazeBarrier();
        addObject(mazeBarrier29,7*50,4*50);
        MazeBarrier mazeBarrier30 = new MazeBarrier();
        addObject(mazeBarrier30,8*50,4*50);
        MazeBarrier mazeBarrier31 = new MazeBarrier();
        addObject(mazeBarrier31,8*50,6*50);
        MazeBarrier mazeBarrier32 = new MazeBarrier();
        addObject(mazeBarrier32,9*50,7*50);
        MazeBarrier mazeBarrier33 = new MazeBarrier();
        addObject(mazeBarrier33,8*50,8*50);
        MazeBarrier mazeBarrier34 = new MazeBarrier();
        addObject(mazeBarrier34,7*50,0);
        MazeBarrier mazeBarrier35 = new MazeBarrier();
        addObject(mazeBarrier35,9*50,0);
        MazeBarrier mazeBarrier36 = new MazeBarrier();
        addObject(mazeBarrier36,8*50,0);
        MazeBarrier mazeBarrier37 = new MazeBarrier();
        addObject(mazeBarrier37,9*50,2*50);
        MazeBarrier mazeBarrier38 = new MazeBarrier();
        addObject(mazeBarrier38,9*50,5*50);
        MazeBarrier mazeBarrier39 = new MazeBarrier();
        addObject(mazeBarrier39,6*50,9*50);
        MazeBarrier mazeBarrier40 = new MazeBarrier();
        addObject(mazeBarrier40,8*50,11*50);
        MazeBarrier mazeBarrier41 = new MazeBarrier();
        addObject(mazeBarrier41,10*50,10*50);
        mazeBarrier10.setLocation(6*50,8*50);
        MazeBarrier mazeBarrier42 = new MazeBarrier();
        addObject(mazeBarrier42,8*50,10*50);
        mazeBarrier31.setLocation(8*50,3*50);
        mazeBarrier30.setLocation(7*50,5*50);
        mazeBarrier38.setLocation(9*50,6*50);
        mazeBarrier24.setLocation(7*50,1*50);
        MazeBarrier mazeBarrier43 = new MazeBarrier();
        addObject(mazeBarrier43,5*50,11*50);
        MazeBarrier mazeBarrier44 = new MazeBarrier();
        addObject(mazeBarrier44,4*50,11*50);
        MazeBarrier mazeBarrier45 = new MazeBarrier();
        addObject(mazeBarrier45,0,2*50);
        MazeBarrier mazeBarrier46 = new MazeBarrier();
        addObject(mazeBarrier46,0,3*50);
        MazeBarrier mazeBarrier47 = new MazeBarrier();
        addObject(mazeBarrier47,0,4*50);
        MazeBarrier mazeBarrier48 = new MazeBarrier();
        addObject(mazeBarrier48,0,1*50);
        MazeBarrier mazeBarrier49 = new MazeBarrier();
        addObject(mazeBarrier49,6*50,0);
        MazeBarrier mazeBarrier50 = new MazeBarrier();
        addObject(mazeBarrier50,2*50,7*50);
        mazeBarrier50.setLocation(4*50,3*50);
        mazeBarrier17.setLocation(1*50,2*50);
        mazeBarrier17.setLocation(1*50,0);
        mazeBarrier13.setLocation(1*50,4*50);
        mazeBarrier44.setLocation(6*50,10*50);
        MazeBarrier mazeBarrier51 = new MazeBarrier();
        addObject(mazeBarrier51,10*50,5*50);
        MazeBarrier mazeBarrier52 = new MazeBarrier();
        addObject(mazeBarrier52,11*50,6*50);
        mazeBarrier31.setLocation(10*50,3*50);
        MazeRunner mazeRunner = new MazeRunner(3);
        addObject(mazeRunner,38,326);
        mazeRunner.setLocation(26,330);
        mazeBarrier7.setLocation(288,588);
        mazeBarrier7.setLocation(315,585);
        mazeBarrier29.setLocation(404,142);
        mazeBarrier35.setLocation(535,11);
        mazeRunner.setLocation(44,329);
        mazeRunner.setLocation(44,329);
        mazeRunner.setLocation(44,329);
        mazeRunner.setLocation(44,329);
        mazeRunner.setLocation(44,329);
        mazeBarrier17.setLocation(8,10);
        MazeBarrier mazeBarrier53 = new MazeBarrier();
        addObject(mazeBarrier53,573,199);
        SpeedUpcheese speedUpcheese = new SpeedUpcheese();
        addObject(speedUpcheese,248,155);
        speedUpcheese.setLocation(248,155);
        SpeedUpcheese speedUpcheese2 = new SpeedUpcheese();
        addObject(speedUpcheese2,248,155);
        SpeedUpcheese speedUpcheese3 = new SpeedUpcheese();
        addObject(speedUpcheese3,49,131);
        SpeedUpcheese speedUpcheese4 = new SpeedUpcheese();
        addObject(speedUpcheese4,500,203);
        SpeedUpcheese speedUpcheese5 = new SpeedUpcheese();
        addObject(speedUpcheese5,561,527);
        SpeedUpcheese speedUpcheese6 = new SpeedUpcheese();
        addObject(speedUpcheese6,304,539);
        speedUpcheese3.setLocation(56,150);
        mazeBarrier46.setLocation(3,153);
        EnimyBird enimyBird = new EnimyBird();
        addObject(enimyBird,3,153);
        mazeBarrier46.setLocation(8,148);
        speedUpcheese5.setLocation(556,528);
        EnimyBird enimyBird2 = new EnimyBird();
        addObject(enimyBird2,556,528);
        speedUpcheese5.setLocation(564,532);
        mazeBarrier7.setLocation(292,589);
        speedUpcheese5.setLocation(11,546);
        enimyBird2.setLocation(50,524);
        speedUpcheese5.setLocation(557,540);
        enimyBird2.setLocation(20,528);
        enimyBird2.setLocation(18,541);
        mazeBarrier47.setLocation(4,195);
        EnimyBird enimyBird3 = new EnimyBird();
        addObject(enimyBird3,4,195);
        mazeBarrier47.setLocation(4,192);
        EnimyBird enimyBird4 = new EnimyBird();
        addObject(enimyBird4,4,192);
        mazeBarrier12.setLocation(11,255);
        EnimyBird enimyBird5 = new EnimyBird();
        addObject(enimyBird5,11,255);
        mazeBarrier12.setLocation(13,259);
        mazeBarrier47.setLocation(3,189);
        mazeBarrier47.setLocation(5,193);
        mazeBarrier8.setLocation(75,423);
        enimyBird2.setLocation(12,546);
        enimyBird2.setLocation(20,536);
        enimyBird2.setLocation(20,536);
        mazeBarrier12.setLocation(12,258);
        mazeBarrier47.setLocation(11,184);
        removeObject(enimyBird4);
        mazeBarrier47.setLocation(5,188);
        removeObject(enimyBird3);
        EnimySnake enimySnake = new EnimySnake(true);
        addObject(enimySnake,247,202);
        enimySnake.setLocation(247,205);
        enimySnake.setLocation(247,203);
        EnimySnake enimySnake2 = new EnimySnake(false);
        addObject(enimySnake2,247,203);
        speedUpcheese5.setLocation(556,535);
        EnimySnake enimySnake3 = new EnimySnake(true);
        addObject(enimySnake3,556,535);
        speedUpcheese5.setLocation(556,535);
        enimySnake3.setLocation(554,525);
        removeObject(enimySnake3);
        EnimySnake enimySnake9 = new EnimySnake(true);
        addObject(enimySnake3,444,18);
        removeObject(mazeBarrier37);
        EnimySnake enimySnake4 = new EnimySnake(false);
        addObject(enimySnake4,288,97);
        MazeBarrier mazeBarrier54 = new MazeBarrier();
        addObject(mazeBarrier54,500,99);
        mazeBarrier54.setLocation(493,103);
        mazeBarrier54.setLocation(513,107);
        mazeBarrier54.setLocation(491,89);
        SpeedUpcheese speedUpcheese7 = new SpeedUpcheese();
        addObject(speedUpcheese7,380,303);
        SpeedUpcheese speedUpcheese8 = new SpeedUpcheese();
        addObject(speedUpcheese8,196,319);
        SpeedUpcheese speedUpcheese9 = new SpeedUpcheese();
        addObject(speedUpcheese9,169,272);
        SpeedUpcheese speedUpcheese10 = new SpeedUpcheese();
        addObject(speedUpcheese10,96,295);
        SpeedUpcheese speedUpcheese11 = new SpeedUpcheese();
        addObject(speedUpcheese11,154,466);
        SpeedUpcheese speedUpcheese12 = new SpeedUpcheese();
        addObject(speedUpcheese12,212,396);
        SpeedUpcheese speedUpcheese13 = new SpeedUpcheese();
        addObject(speedUpcheese13,183,521);
        SpeedUpcheese speedUpcheese14 = new SpeedUpcheese();
        addObject(speedUpcheese14,465,548);
        SpeedUpcheese speedUpcheese15 = new SpeedUpcheese();
        addObject(speedUpcheese15,526,399);
        SpeedUpcheese speedUpcheese16 = new SpeedUpcheese();
        addObject(speedUpcheese16,408,228);
        SpeedUpcheese speedUpcheese17 = new SpeedUpcheese();
        addObject(speedUpcheese17,427,93);
        SpeedUpcheese speedUpcheese18 = new SpeedUpcheese();
        addObject(speedUpcheese18,173,52);
        enimySnake.setLocation(244,197);
        removeObject(enimySnake2);
        EnimySnake enimySnake14 = new EnimySnake(false);
        addObject(enimySnake2,246,243);
        enimySnake2.setLocation(246,251);
        YouWinPlatform youWinPlatform = new YouWinPlatform();
        addObject(youWinPlatform,571,72);
        youWinPlatform.setLocation(575,72);
        removeObject(mazeBarrier35);
        youWinPlatform.setLocation(567,48);
        youWinPlatform.setLocation(568,33);
        youWinPlatform.setLocation(556,20);
        youWinPlatform.setLocation(585,52);
        youWinPlatform.setLocation(580,48);
        youWinPlatform.setLocation(581,60);
        youWinPlatform.setLocation(561,51);
        youWinPlatform.setLocation(570,52);
        youWinPlatform.setLocation(584,45);
        mazeBarrier54.setLocation(493,31);
        youWinPlatform.setLocation(567,64);
        mazeBarrier54.setLocation(502,26);
        mazeBarrier31.setLocation(495,114);
        EnimySnake enimySnake5 = new EnimySnake(true);
        addObject(enimySnake5,492,156);
        removeObject(speedUpcheese13);
        removeObject(speedUpcheese14);
        removeObject(speedUpcheese8);
        removeObject(speedUpcheese9);
        removeObject(speedUpcheese16);
        removeObject(speedUpcheese7);
        speedUpcheese12.setLocation(208,394);
        removeObject(speedUpcheese12);
        removeObject(speedUpcheese10);
    }
}
